### ISSUE TITLE
Mystery Guest: Identify the test by line

### ISSUE THREAD

**Issue by danielevalverde** [tassiovirginio/jnose#17]

**Comment by luana-martins** [comment]
**Description.** Mystery Guest (MG) occurs when a test method utilizes external resources (e.g. files, database, etc.). Use of external resources in test methods will result in stability and performance issues. Developers should use mock objects in place of external resources.

**Detection.** A test containing object instances of files and databases classes.

**Problem.** The MG detection is not pointing to the line where the object instances files or databases classes.  Fix the test smell detection to count each of its instances and to point the line location.
