### ISSUE TITLE
Redundant Assertion

### ISSUE THREAD

**Issue by danielevalverde** [tassiovirginio/jnose#21]

**Comment by luana-martins** [comment]
**Description:** Redundant Assertion (RA) smell occurs when test methods contain assertion statements that are either always true or always false. RA is introduced by developers for debugging purposes and then forgotten.

**Detection.** Assertion statement in which the expected and actual parameters are the same.

**Problem.** Only one RA is detected in the test method, even if the test method has multiple assertions with the same expected and actual parameters. Fix the test smell detection to count each of its instances and to point the line location.
